channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-tidyverse

  # Rmarkdown
  - r-markdown
  - r-kableextra
  - r-janitor
  - r-english

  # machine learning
  - r-glmnet
  - r-randomforest
  - bioconductor-mixomics    # datasets for exercises

